### ISSUE TITLE
Feedback documentatie

### ISSUE THREAD

**Issue by roberrrt-s** [emmaoudmaijer/functional-programming#10]
Hi Emma,

Goed om te zien waar je gekomen bent tov. afgelopen zondag, je wiki ziet er goed uit, ik kan je proces volgen en je legt alle stappen die je maakt goed uit. + een uitstekende bronvermelding!
Er is nog wel een kapotte image onderaan deze pagina: https://github.com/emmaoudmaijer/functional-programming/wiki/Data-cleaning
Verder, veel succes morgen!

**Comment by emmaoudmaijer** [comment]
Image vervangen door de juiste. Dankjewel voor je feedback!!
